### ISSUE TITLE
Change app icon and text

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#114]
> If it's not too much trouble, could you change the app icon to the image that is attached? Also, what do you think about changing the text that displays below the icon from "Utah Wildlife-Vehicle Collision Reporter" to just "WVC Reporter" so all the text will display?

App icon png is [here](https://drive.google.com/drive/folders/1sGy-q8ZH5KXFwo-hGymFxzFNy7VG6Mga).

**Comment by stdavis** [comment]
Still need to:
- [ ] update icon on app store
- [ ] update icon on google play
- [ ] update app text in both of these places as well

**Comment by stdavis** [comment]
Looks like the apple automatically removed the space in iOS so that it shows a "WVCReporter". I assume that [it is because the name is still a bit long](https://github.com/fastlane/fastlane/issues/12154#issuecomment-376907942). I don't think that it's a big deal. I'm just adding this note for future reference.

**Comment by nathankota** [comment]
This looks great to me. Going to close and if there is more feedback we can reopen or start another issue.
