### ISSUE TITLE
Put species workflow at top of reporting/pickup

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#129]
Reorder the reporting and pickup dialogs to have the species identification, age, and sex components first, followed by dates, photos, comments, repeat submission. Repeat submission _might_ make sense to keep at the top.

**Comment by stdavis** [comment]
I kept the repeat submission above the discovered date just because it's much easier the way that I have things set up. If the client really wants it moved somewhere else, I will do it.

![image](https://user-images.githubusercontent.com/1326248/142520845-0c397da6-2f83-4ca7-bb18-5882afb4f681.png)
![image](https://user-images.githubusercontent.com/1326248/142520969-b2eef162-c2ab-4109-ba73-eff21964b8c1.png)

**Comment by nathankota** [comment]
validated
