### ISSUE TITLE
Part of route map cut off of Route Info

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#167]
There were 5 pickups, and only four are displayed, but _maybe_ one of them was an observation and not a pickup, so that's why it's not appearing? I'm not sure if that's the reason, or if the map isn't quite displaying the full north end of the route.

![Screenshot_20220217-164127](https://user-images.githubusercontent.com/15659642/154591646-9a529582-d2d2-4263-bcfc-a76a49757d79.png)

**Comment by stdavis** [comment]
Observations are not associated with a route so it would not show up in the route info page.

The padding (or lack thereof) around the features on the map is an [upstream, Android-only bug](https://github.com/react-native-maps/react-native-maps/issues/3603) that appears to have been fixed in the latest version. The only issue is that I'm not sure that the newest version is compatible with expo. I'll have to investigate and give it a try.

**Comment by stdavis** [comment]
This possibly will be fixed by #187

**Comment by nathankota** [comment]
It looks about the same to me, but I haven't heard about this from anyone else, so let's close this issue and see if it comes up again as app usage increases. 

![image](https://user-images.githubusercontent.com/15659642/208496799-396cb7d2-caa8-4b21-8fa4-6d5efa4b5014.png)
