### ISSUE TITLE
Import Legacy Data

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#27]
Write a script to import/ETL data from the legacy database and set up a process to make it repeatable so that any new data they enter via the [desktop app](https://mapserv.utah.gov/wvc/desktop/map.php) will be imported.

**Comment by nathankota** [comment]
Do you think this should be part of the "prod-ready" milestone? I'm thinking not, but would like your take on it.

**Comment by stdavis** [comment]
I agree. This can come later and has no effect on the prod app.

**Comment by nathankota** [comment]
@jshapiro49 Do these look like the fields we need to migrate to the new database? 

| SDE DB | Postgres DB |
| -------- | ------------- |
| Reports.REPORT_DATE | pickup_reports.pickup_date **OR** report_id.submit_date ? |
| Reports.SPECIES | report_infos.common_name, (**also need to populate:** species_id, scientific_name, species_type, species_class, species_order, family) |
| Reports.AGE_CLASS | report_infos.age_class |
| Reports.GENDER | report_infos.sex |
|  | geography_columns | 
|  | geometry_columns |
|  | spatial_ref_system |
|  | knex_migrations |

**Comment by jshapiro49** [comment]
-  If it's a contractor submission, we can assume the Reports.REPORT_DATE should populate the pickup_reports.pickup date, but let me double-check with the DWR team.

-  There are some standardization issues in the SDE Reports.SPECIES field (e.g., mule, Deer, Mule Deer, antelope, Antelope, etc.). Otherwise, Reports.SPECIES should map to the report_infos.common_name field in the new database. 

- We also want to map the responder name, email, and responder agency to the users' and organization tables: 

Reports.Responder_Email = users.email
Reports.Responder_Agency = organizations.org_type
Reports.Responder_Name = users.first_name & users.last_name
Reports.Comments = report_infos.comments

**Comment by nathankota** [comment]
@jshapiro49 if we can get you access to the cloud sql database are you willing to help migrate data?

**Comment by jshapiro49** [comment]
@nathankota I'd be happy to help.
