### ISSUE TITLE
Offline Maps

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#29]
Add support for offline maps for navigation when the device is offline.

From the SOW:
> * Offline capability to collect data, then sync to database when network connectivity is
available.
> * Offline maps and data collection
> * Offline data storage and pushing data to database

See the [Development Plan](https://docs.google.com/document/d/1ov5tFX-dcNkqvn7aCzUCsaMyhyBOdDq5ECVPCN-0o54/edit#heading=h.m0oeypeujdgf) for more info.

**Comment by stdavis** [comment]
@nathankota I'm not sure what you want to do with this issue. It's partially addressed. Any tiles that you browse to, when online, are cached and will be used offline.

**Comment by nathankota** [comment]
This works well to show the cached tiles, and I also prefer that the user must actively send their unsubmitted reports, rather than it happening automatically when back online. We _might_ need some sort of notification when users go offline, or at some other point, to let them know only the cached tiles will appear offline. For now, I think this is good.

![image](https://user-images.githubusercontent.com/15659642/163888846-d9e2a5b7-54fb-404b-9750-5051c3a8c4ba.png)
